# Generated by Django 2.1.4 on 2018-12-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tppo', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
    ]
