# Generated by Django 2.1.4 on 2018-12-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tppo', '0005_auto_20181220_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='poper',
            field=models.IntegerField(default=0),
        ),
    ]
