# Generated by Django 2.1.3 on 2019-05-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tppo', '0006_choice_poper'),
    ]

    operations = [
        migrations.CreateModel(
            name='theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thmname', models.CharField(max_length=50)),
            ],
        ),
    ]
