# Generated by Django 2.1.3 on 2019-05-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tppo', '0007_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thmname', models.CharField(max_length=50)),
                ('keke', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='theme',
        ),
    ]
