# Generated by Django 2.1.3 on 2019-05-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tppo', '0009_auto_20190510_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keks',
            old_name='keke',
            new_name='thmname',
        ),
    ]
