# Generated by Django 2.1.3 on 2019-06-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tppo', '0012_auto_20190602_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='grammar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
